[project]
name = "finpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pandas>=2.2.3",
    "sqlmodel>=0.0.24",
]
