"""Added index to dato field

Revision ID: 85826dcb04b5
Revises: c12584dfa291
Create Date: 2025-06-01 11:46:17.731888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '85826dcb04b5'
down_revision: Union[str, None] = 'c12584dfa291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_dato'), 'transactions', ['dato'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_dato'), table_name='transactions')
    # ### end Alembic commands ###
