"""Added transactions table

Revision ID: c12584dfa291
Revises: 
Create Date: 2025-06-01 10:51:58.301814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c12584dfa291'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dato', sa.Date(), nullable=False),
    sa.Column('inn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ut', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tilkonto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tilkonto_nr', sa.BigInteger(), nullable=True),
    sa.Column('frakonto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('frakonto_nr', sa.BigInteger(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tekst', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('kid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hovedkategori', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('underkategori', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
